### ISSUE TITLE
Split out category field

### ISSUE THREAD

**Issue by nickevansuk** [britishtriathlon/openactive#3]
Thanks to [getthedata.com](https://www.getthedata.com/openactive/british-triathlon/data-profile), the values of `category` are currently as below, and can be mapped to other fields, removing the need to include `category` as it is currently rendered:

- `Adult / Age Group` -> `"ageRange": { "minValue": 18 }`
- `Children / Tri Star (8-14 yrs)`-> `"ageRange": { "minValue": 8, "maxValue": 14 }`
- `Elite` -> `"level": "Elite"`
- `Go Tri / Beginner` -> `"level": "Beginner"` (noting this is already captured by `programme` too)
- `Paratriathletes` -> `"accessibilitySupport": [ "Paratriathletes" ]`
- `Youth and Junior (15-19 yrs)`  -> `"ageRange": { "minValue": 15, "maxValue": 19 }`

**Comment by matthew-coffey** [comment]
This has been done in the latest update
